[package]
name = "py-call-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "py_call_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
opencv = "0.88.5"
numpy = "0.20.0"